# Generated by Django 4.2.1 on 2023-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_visitor_alter_album_artist_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
