# Generated by Django 4.2.1 on 2023-05-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_remove_artist_name_artist_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist',
            new_name='artist_name',
        ),
    ]
