# Generated by Django 4.2.1 on 2023-05-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_rename_artist_artist_artist_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
