# Generated by Django 4.2.1 on 2023-05-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_artist_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_name',
            new_name='name',
        ),
    ]
